/*
 * tc_error_correction_cw.c
 *
 *  Created on: Dec 1, 2015
 *      Author: tungnt
 */
#include "../test_include/test_case.h"

START_TEST(tc_error_correction_cw_tc1){
	int check = FALSE;
	error_collection_cw_t data_test,data_true;
	data_true.total_data_cw = 19;
	data_true.ec_cw_per_block = 7;
	data_true.num_block_group1 = 1;
	data_true.num_cw_block_group1 = 19;
	data_true.num_block_group2 = 0;
	data_true.num_cw_block_group2 = 0;
	data_test = error_correction_cw(VERSION_1, LEVEL_L);
	check = check_data_error_correction_cw(data_test,data_true);
	ck_assert_int_eq(check,TRUE);
}END_TEST
START_TEST(tc_error_correction_cw_tc2){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 16;data_true.ec_cw_per_block = 10;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_1, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc3){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 13;data_true.ec_cw_per_block = 13;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 13;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_1, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc4){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 9;data_true.ec_cw_per_block = 17;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 9;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_1, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc5){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 34;data_true.ec_cw_per_block = 10;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 34;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_2, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc6){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 28;data_true.ec_cw_per_block = 16;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 28;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_2, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc7){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 22;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_2, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc8){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 16;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_2, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc9){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 55;data_true.ec_cw_per_block = 15;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 55;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_3, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc10){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 44;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 44;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_3, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc11){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 34;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 17;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_3, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc12){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 26;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 13;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_3, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc13){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 80;data_true.ec_cw_per_block = 20;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 80;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_4, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc14){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 64;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 32;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_4, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc15){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 48;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_4, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc16){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 36;data_true.ec_cw_per_block = 16;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 9;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_4, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc17){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 108;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 108;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_5, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc18){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 86;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 43;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_5, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc19){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 62;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_5, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc20){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 46;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 11;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 12;data_test = error_correction_cw(VERSION_5, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc21){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 136;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 68;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_6, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc22){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 108;data_true.ec_cw_per_block = 16;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 27;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_6, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc23){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 76;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 19;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_6, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc24){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 60;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_6, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc25){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 156;data_true.ec_cw_per_block = 20;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 78;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_7, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc26){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 124;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 31;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_7, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc27){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 88;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 14;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 15;data_test = error_correction_cw(VERSION_7, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc28){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 66;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 13;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 14;data_test = error_correction_cw(VERSION_7, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc29){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 194;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 97;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_8, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc30){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 154;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 38;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 39;data_test = error_correction_cw(VERSION_8, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc31){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 110;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 18;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 19;data_test = error_correction_cw(VERSION_8, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc32){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 86;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 14;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 15;data_test = error_correction_cw(VERSION_8, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc33){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 232;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 116;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_9, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc34){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 182;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 36;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 37;data_test = error_correction_cw(VERSION_9, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc35){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 132;data_true.ec_cw_per_block = 20;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_9, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc36){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 100;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 12;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 13;data_test = error_correction_cw(VERSION_9, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc37){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 274;data_true.ec_cw_per_block = 18;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 68;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 69;data_test = error_correction_cw(VERSION_10, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc38){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 216;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 43;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 44;data_test = error_correction_cw(VERSION_10, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc39){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 154;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 19;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 20;data_test = error_correction_cw(VERSION_10, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc40){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 122;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_10, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc41){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 324;data_true.ec_cw_per_block = 20;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 81;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_11, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc42){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 254;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 50;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 51;data_test = error_correction_cw(VERSION_11, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc43){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 180;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 23;data_test = error_correction_cw(VERSION_11, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc44){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 140;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 12;data_true.num_block_group2 = 8;data_true.num_cw_block_group2 = 13;data_test = error_correction_cw(VERSION_11, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc45){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 370;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 92;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 93;data_test = error_correction_cw(VERSION_12, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc46){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 290;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 36;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 37;data_test = error_correction_cw(VERSION_12, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc47){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 206;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 20;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 21;data_test = error_correction_cw(VERSION_12, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc48){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 158;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 7;data_true.num_cw_block_group1 = 14;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 15;data_test = error_correction_cw(VERSION_12, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc49){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 428;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 107;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_13, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc50){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 334;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 37;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 38;data_test = error_correction_cw(VERSION_13, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc51){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 244;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 20;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 21;data_test = error_correction_cw(VERSION_13, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc52){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 180;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 12;data_true.num_cw_block_group1 = 11;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 12;data_test = error_correction_cw(VERSION_13, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc53){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 461;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 116;data_test = error_correction_cw(VERSION_14, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc54){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 365;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 40;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 41;data_test = error_correction_cw(VERSION_14, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc55){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 261;data_true.ec_cw_per_block = 20;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_14, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc56){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 197;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 12;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 13;data_test = error_correction_cw(VERSION_14, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc57){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 523;data_true.ec_cw_per_block = 22;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 87;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 88;data_test = error_correction_cw(VERSION_15, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc58){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 415;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 41;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 42;data_test = error_correction_cw(VERSION_15, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc59){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 295;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_15, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc60){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 223;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 12;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 13;data_test = error_correction_cw(VERSION_15, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc61){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 589;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 98;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 99;data_test = error_correction_cw(VERSION_16, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc62){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 453;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 7;data_true.num_cw_block_group1 = 45;data_true.num_block_group2 = 3;data_true.num_cw_block_group2 = 46;data_test = error_correction_cw(VERSION_16, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc63){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 325;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 15;data_true.num_cw_block_group1 = 19;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 20;data_test = error_correction_cw(VERSION_16, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc64){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 253;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 13;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_16, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc65){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 647;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 107;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 108;data_test = error_correction_cw(VERSION_17, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc66){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 507;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 10;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_17, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc67){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 367;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 15;data_true.num_cw_block_group2 = 23;data_test = error_correction_cw(VERSION_17, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc68){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 283;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 14;data_true.num_block_group2 = 17;data_true.num_cw_block_group2 = 15;data_test = error_correction_cw(VERSION_17, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc69){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 721;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 120;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 121;data_test = error_correction_cw(VERSION_18, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc70){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 563;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 9;data_true.num_cw_block_group1 = 43;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 44;data_test = error_correction_cw(VERSION_18, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc71){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 397;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 23;data_test = error_correction_cw(VERSION_18, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc72){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 313;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 14;data_true.num_block_group2 = 19;data_true.num_cw_block_group2 = 15;data_test = error_correction_cw(VERSION_18, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc73){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 795;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 113;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 114;data_test = error_correction_cw(VERSION_19, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc74){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 627;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 44;data_true.num_block_group2 = 11;data_true.num_cw_block_group2 = 45;data_test = error_correction_cw(VERSION_19, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc75){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 445;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 21;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 22;data_test = error_correction_cw(VERSION_19, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc76){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 341;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 9;data_true.num_cw_block_group1 = 13;data_true.num_block_group2 = 16;data_true.num_cw_block_group2 = 14;data_test = error_correction_cw(VERSION_19, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc77){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 861;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 107;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 108;data_test = error_correction_cw(VERSION_20, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc78){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 669;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 41;data_true.num_block_group2 = 13;data_true.num_cw_block_group2 = 42;data_test = error_correction_cw(VERSION_20, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc79){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 485;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 15;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_20, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc80){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 385;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 15;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_20, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc81){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 932;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 116;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 117;data_test = error_correction_cw(VERSION_21, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc82){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 714;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 42;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_21, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc83){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 512;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 23;data_test = error_correction_cw(VERSION_21, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc84){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 406;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_21, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc85){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1006;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 111;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 112;data_test = error_correction_cw(VERSION_22, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc86){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 782;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_22, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc87){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 568;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 7;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 16;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_22, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc88){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 442;data_true.ec_cw_per_block = 24;data_true.num_block_group1 = 34;data_true.num_cw_block_group1 = 13;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_22, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc89){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1094;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 121;data_true.num_block_group2 = 5;data_true.num_cw_block_group2 = 122;data_test = error_correction_cw(VERSION_23, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc90){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 860;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_23, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc91){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 614;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_23, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc92){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 464;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 16;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_23, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc93){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1174;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 117;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 118;data_test = error_correction_cw(VERSION_24, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc94){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 914;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 45;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 46;data_test = error_correction_cw(VERSION_24, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc95){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 664;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 16;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_24, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc96){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 514;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 30;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_24, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc97){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1276;data_true.ec_cw_per_block = 26;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 106;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 107;data_test = error_correction_cw(VERSION_25, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc98){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1000;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 13;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_25, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc99){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 718;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 7;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 22;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_25, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc100){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 538;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 22;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 13;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_25, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc101){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1370;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 10;data_true.num_cw_block_group1 = 114;data_true.num_block_group2 = 2;data_true.num_cw_block_group2 = 115;data_test = error_correction_cw(VERSION_26, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc102){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1062;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_26, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc103){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 754;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 28;data_true.num_cw_block_group1 = 22;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 23;data_test = error_correction_cw(VERSION_26, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc104){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 596;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 33;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_26, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc105){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1468;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 122;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 123;data_test = error_correction_cw(VERSION_27, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc106){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1128;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 22;data_true.num_cw_block_group1 = 45;data_true.num_block_group2 = 3;data_true.num_cw_block_group2 = 46;data_test = error_correction_cw(VERSION_27, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc107){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 808;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 8;data_true.num_cw_block_group1 = 23;data_true.num_block_group2 = 26;data_true.num_cw_block_group2 = 24;data_test = error_correction_cw(VERSION_27, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc108){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 628;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 12;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 28;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_27, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc109){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1531;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 117;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 118;data_test = error_correction_cw(VERSION_28, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc110){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1193;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 3;data_true.num_cw_block_group1 = 45;data_true.num_block_group2 = 23;data_true.num_cw_block_group2 = 46;data_test = error_correction_cw(VERSION_28, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc111){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 871;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 31;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_28, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc112){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 661;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 31;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_28, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc113){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1631;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 7;data_true.num_cw_block_group1 = 116;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 117;data_test = error_correction_cw(VERSION_29, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc114){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1267;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 21;data_true.num_cw_block_group1 = 45;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 46;data_test = error_correction_cw(VERSION_29, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc115){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 911;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 1;data_true.num_cw_block_group1 = 23;data_true.num_block_group2 = 37;data_true.num_cw_block_group2 = 24;data_test = error_correction_cw(VERSION_29, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc116){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 701;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 26;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_29, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc117){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1735;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 5;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 116;data_test = error_correction_cw(VERSION_30, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc118){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1373;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_30, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc119){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 985;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 15;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 25;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_30, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc120){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 745;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 23;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 25;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_30, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc121){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1843;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 13;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 3;data_true.num_cw_block_group2 = 116;data_test = error_correction_cw(VERSION_31, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc122){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1455;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 29;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_31, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc123){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1033;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 42;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_31, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc124){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 793;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 23;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 28;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_31, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc125){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1955;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 0;data_true.num_cw_block_group2 = 0;data_test = error_correction_cw(VERSION_32, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc126){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1541;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 10;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 23;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_32, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc127){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1115;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 10;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 35;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_32, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc128){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 845;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 35;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_32, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc129){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2071;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 116;data_test = error_correction_cw(VERSION_33, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc130){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1631;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 14;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 21;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_33, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc131){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1171;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 29;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 19;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_33, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc132){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 901;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 11;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 46;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_33, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc133){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2191;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 13;data_true.num_cw_block_group1 = 115;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 116;data_test = error_correction_cw(VERSION_34, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc134){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1725;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 14;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 23;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_34, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc135){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1231;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 44;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_34, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc136){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 961;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 59;data_true.num_cw_block_group1 = 16;data_true.num_block_group2 = 1;data_true.num_cw_block_group2 = 17;data_test = error_correction_cw(VERSION_34, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc137){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2306;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 12;data_true.num_cw_block_group1 = 121;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 122;data_test = error_correction_cw(VERSION_35, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc138){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1812;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 12;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 26;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_35, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc139){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1286;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 39;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_35, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc140){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 986;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 22;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 41;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_35, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc141){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2434;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 121;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 122;data_test = error_correction_cw(VERSION_36, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc142){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1914;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 6;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 34;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_36, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc143){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1354;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 46;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_36, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc144){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1054;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 2;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 64;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_36, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc145){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2566;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 17;data_true.num_cw_block_group1 = 122;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 123;data_test = error_correction_cw(VERSION_37, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc146){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1992;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 29;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_37, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc147){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1426;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 49;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 10;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_37, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc148){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1096;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 24;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 46;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_37, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc149){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2702;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 4;data_true.num_cw_block_group1 = 122;data_true.num_block_group2 = 18;data_true.num_cw_block_group2 = 123;data_test = error_correction_cw(VERSION_38, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc150){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2102;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 13;data_true.num_cw_block_group1 = 46;data_true.num_block_group2 = 32;data_true.num_cw_block_group2 = 47;data_test = error_correction_cw(VERSION_38, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc151){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1502;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 48;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 14;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_38, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc152){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1142;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 42;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 32;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_38, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc153){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2812;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 20;data_true.num_cw_block_group1 = 117;data_true.num_block_group2 = 4;data_true.num_cw_block_group2 = 118;data_test = error_correction_cw(VERSION_39, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc154){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2216;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 40;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 7;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_39, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc155){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1582;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 43;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 22;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_39, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc156){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1222;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 10;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 67;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_39, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc157){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2956;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 19;data_true.num_cw_block_group1 = 118;data_true.num_block_group2 = 6;data_true.num_cw_block_group2 = 119;data_test = error_correction_cw(VERSION_40, LEVEL_L);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc158){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 2334;data_true.ec_cw_per_block = 28;data_true.num_block_group1 = 18;data_true.num_cw_block_group1 = 47;data_true.num_block_group2 = 31;data_true.num_cw_block_group2 = 48;data_test = error_correction_cw(VERSION_40, LEVEL_M);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc159){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1666;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 34;data_true.num_cw_block_group1 = 24;data_true.num_block_group2 = 34;data_true.num_cw_block_group2 = 25;data_test = error_correction_cw(VERSION_40, LEVEL_Q);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
START_TEST(tc_error_correction_cw_tc160){int check = FALSE;error_collection_cw_t data_test,data_true;data_true.total_data_cw = 1276;data_true.ec_cw_per_block = 30;data_true.num_block_group1 = 20;data_true.num_cw_block_group1 = 15;data_true.num_block_group2 = 61;data_true.num_cw_block_group2 = 16;data_test = error_correction_cw(VERSION_40, LEVEL_H);check = check_data_error_correction_cw(data_test,data_true);ck_assert_int_eq(check,TRUE);}END_TEST
TCase* tc_error_correction_cw() {
	TCase* tc_error_correction_cw = tcase_create("tc_error_correction_cw_test");
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc1);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc2);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc3);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc4);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc5);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc6);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc7);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc8);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc9);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc10);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc11);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc12);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc13);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc14);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc15);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc16);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc17);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc18);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc19);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc20);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc21);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc22);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc23);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc24);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc25);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc26);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc27);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc28);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc29);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc30);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc31);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc32);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc33);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc34);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc35);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc36);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc37);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc38);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc39);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc40);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc41);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc42);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc43);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc44);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc45);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc46);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc47);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc48);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc49);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc50);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc51);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc52);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc53);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc54);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc55);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc56);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc57);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc58);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc59);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc60);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc61);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc62);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc63);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc64);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc65);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc66);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc67);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc68);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc69);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc70);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc71);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc72);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc73);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc74);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc75);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc76);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc77);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc78);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc79);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc80);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc81);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc82);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc83);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc84);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc85);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc86);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc87);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc88);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc89);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc90);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc91);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc92);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc93);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc94);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc95);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc96);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc97);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc98);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc99);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc100);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc101);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc102);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc103);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc104);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc105);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc106);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc107);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc108);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc109);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc110);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc111);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc112);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc113);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc114);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc115);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc116);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc117);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc118);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc119);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc120);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc121);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc122);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc123);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc124);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc125);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc126);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc127);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc128);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc129);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc130);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc131);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc132);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc133);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc134);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc135);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc136);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc137);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc138);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc139);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc140);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc141);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc142);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc143);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc144);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc145);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc146);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc147);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc148);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc149);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc150);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc151);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc152);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc153);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc154);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc155);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc156);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc157);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc158);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc159);
	tcase_add_test(tc_error_correction_cw,tc_error_correction_cw_tc160);
	return tc_error_correction_cw;
}

