/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qrNativeC_NativeClassC */

#ifndef _Included_qrNativeC_NativeClassC
#define _Included_qrNativeC_NativeClassC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qrNativeC_NativeClassC
 * Method:    printdata
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_qrNativeC_NativeClassC_printdata
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
